### ISSUE TITLE
Missing "type" property for serverless CLI options

### ISSUE THREAD

**Issue by captaincode-generic** [EliuX/serverless-migrate-plugin#25]
When running this plugin commands with serverless, like `sls migrate create -n <your-migration-name>`

We are getting next warning:

```
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - MigratePlugin for "state-file", "store", "date-format", "file-extension", "name", "template-file"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
```

According to  [this](https://www.serverless.com/framework/docs/deprecations/#cli-options-extensions-type-requirement):

> Starting with v3.0.0 any option extensions which does not have type defined will be communicated with a thrown error

To fix this, the **type** property should be added to the options:
- state-file
- store
- date-format
- file-extension
- name
- template-file

**Comment by EliuX** [comment]
Thanks for your collaboration
